In [1]:
from __future__ import print_function
import torch

    Input all the needed libraries 

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0328, 0.7445, 0.3917],
        [0.2863, 0.5991, 0.7014],
        [0.9939, 0.3016, 0.4412],
        [0.4522, 0.2882, 0.4626],
        [0.3676, 0.4063, 0.5302]])


In [3]:
#x = torch.zeros(5, 3, dtype=torch.float32); 
x = torch.zeros([2, 4], dtype=torch.int32)

print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[2.7822e-02, 4.5814e-41, 2.7822e-02],
        [4.5814e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.6243e-44, 0.0000e+00],
        [2.1617e+23, 3.0900e-41, 2.2045e+23]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])
