In [1]:
from __future__ import print_function
import torch

    Input all the needed libraries 

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0328, 0.7445, 0.3917],
        [0.2863, 0.5991, 0.7014],
        [0.9939, 0.3016, 0.4412],
        [0.4522, 0.2882, 0.4626],
        [0.3676, 0.4063, 0.5302]])


In [3]:
#x = torch.zeros(5, 3, dtype=torch.float32); 
x = torch.zeros([2, 4], dtype=torch.int32)

print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[2.7822e-02, 4.5814e-41, 2.7822e-02],
        [4.5814e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.6243e-44, 0.0000e+00],
        [2.1617e+23, 3.0900e-41, 2.2045e+23]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6663, -0.4142, -0.4094],
        [-0.0502,  0.6737,  0.1680],
        [-0.3468, -0.3204,  1.6398],
        [-0.5864,  0.5514,  1.8311],
        [ 0.4548, -0.4596, -0.1846]])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.6186, -0.1377, -0.3281],
        [ 0.8364,  1.0089,  0.3170],
        [ 0.2031,  0.3707,  2.2550],
        [-0.3966,  0.8943,  2.1270],
        [ 1.2084, -0.4229,  0.4784]])


In [9]:
print(torch.add(x, y))

tensor([[-1.6186, -0.1377, -0.3281],
        [ 0.8364,  1.0089,  0.3170],
        [ 0.2031,  0.3707,  2.2550],
        [-0.3966,  0.8943,  2.1270],
        [ 1.2084, -0.4229,  0.4784]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.6186, -0.1377, -0.3281],
        [ 0.8364,  1.0089,  0.3170],
        [ 0.2031,  0.3707,  2.2550],
        [-0.3966,  0.8943,  2.1270],
        [ 1.2084, -0.4229,  0.4784]])


In [11]:
y.add_(x)
print(y)

tensor([[-1.6186, -0.1377, -0.3281],
        [ 0.8364,  1.0089,  0.3170],
        [ 0.2031,  0.3707,  2.2550],
        [-0.3966,  0.8943,  2.1270],
        [ 1.2084, -0.4229,  0.4784]])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3304])
0.330412358045578


# NUMPY BRIDGE

In [14]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else: 
    print("cpu")

cpu
